# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import polargraph_pb2 as polargraph__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in polargraph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolarGraphServiceStub:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/Insert',
                request_serializer=polargraph__pb2.InsertRequest.SerializeToString,
                response_deserializer=polargraph__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/Query',
                request_serializer=polargraph__pb2.QueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.InsertVector = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/InsertVector',
                request_serializer=polargraph__pb2.InsertVectorRequest.SerializeToString,
                response_deserializer=polargraph__pb2.InsertVectorResponse.FromString,
                _registered_method=True)
        self.SearchVector = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/SearchVector',
                request_serializer=polargraph__pb2.SearchVectorRequest.SerializeToString,
                response_deserializer=polargraph__pb2.SearchVectorResponse.FromString,
                _registered_method=True)
        self.Reachable = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/Reachable',
                request_serializer=polargraph__pb2.ReachableRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ReachableResponse.FromString,
                _registered_method=True)
        self.RegisterNodeType = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/RegisterNodeType',
                request_serializer=polargraph__pb2.RegisterNodeTypeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.RegisterNodeTypeResponse.FromString,
                _registered_method=True)
        self.GetNodeType = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/GetNodeType',
                request_serializer=polargraph__pb2.GetNodeTypeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.GetNodeTypeResponse.FromString,
                _registered_method=True)
        self.ListNodeTypes = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ListNodeTypes',
                request_serializer=polargraph__pb2.ListNodeTypesRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ListNodeTypesResponse.FromString,
                _registered_method=True)
        self.ValidateNode = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ValidateNode',
                request_serializer=polargraph__pb2.ValidateNodeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ValidateNodeResponse.FromString,
                _registered_method=True)
        self.RegisterEdgeType = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/RegisterEdgeType',
                request_serializer=polargraph__pb2.RegisterEdgeTypeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.RegisterEdgeTypeResponse.FromString,
                _registered_method=True)
        self.GetEdgeType = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/GetEdgeType',
                request_serializer=polargraph__pb2.GetEdgeTypeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.GetEdgeTypeResponse.FromString,
                _registered_method=True)
        self.ListEdgeTypes = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ListEdgeTypes',
                request_serializer=polargraph__pb2.ListEdgeTypesRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ListEdgeTypesResponse.FromString,
                _registered_method=True)
        self.ValidateEdge = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ValidateEdge',
                request_serializer=polargraph__pb2.ValidateEdgeRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ValidateEdgeResponse.FromString,
                _registered_method=True)
        self.ListPredicatesBetween = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ListPredicatesBetween',
                request_serializer=polargraph__pb2.ListPredicatesBetweenRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ListPredicatesBetweenResponse.FromString,
                _registered_method=True)
        self.SearchVectorFiltered = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/SearchVectorFiltered',
                request_serializer=polargraph__pb2.SearchVectorFilteredRequest.SerializeToString,
                response_deserializer=polargraph__pb2.SearchVectorFilteredResponse.FromString,
                _registered_method=True)
        self.SearchVectorInSet = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/SearchVectorInSet',
                request_serializer=polargraph__pb2.SearchVectorInSetRequest.SerializeToString,
                response_deserializer=polargraph__pb2.SearchVectorInSetResponse.FromString,
                _registered_method=True)
        self.BatchInsertVectors = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/BatchInsertVectors',
                request_serializer=polargraph__pb2.BatchInsertVectorsRequest.SerializeToString,
                response_deserializer=polargraph__pb2.BatchInsertVectorsResponse.FromString,
                _registered_method=True)
        self.VectorSeedQuery = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/VectorSeedQuery',
                request_serializer=polargraph__pb2.VectorSeedQueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.VectorSeedQueryResponse.FromString,
                _registered_method=True)
        self.CreateBackup = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/CreateBackup',
                request_serializer=polargraph__pb2.CreateBackupRequest.SerializeToString,
                response_deserializer=polargraph__pb2.CreateBackupResponse.FromString,
                _registered_method=True)
        self.ListBackups = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ListBackups',
                request_serializer=polargraph__pb2.ListBackupsRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ListBackupsResponse.FromString,
                _registered_method=True)
        self.PurgeOldBackups = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/PurgeOldBackups',
                request_serializer=polargraph__pb2.PurgeOldBackupsRequest.SerializeToString,
                response_deserializer=polargraph__pb2.PurgeOldBackupsResponse.FromString,
                _registered_method=True)
        self.RunRetention = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/RunRetention',
                request_serializer=polargraph__pb2.RunRetentionRequest.SerializeToString,
                response_deserializer=polargraph__pb2.RunRetentionResponse.FromString,
                _registered_method=True)
        self.ReplicaStatus = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ReplicaStatus',
                request_serializer=polargraph__pb2.ReplicaStatusRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ReplicaStatusResponse.FromString,
                _registered_method=True)
        self.StreamWal = channel.unary_stream(
                '/polargraph.v1.PolarGraphService/StreamWal',
                request_serializer=polargraph__pb2.StreamWalRequest.SerializeToString,
                response_deserializer=polargraph__pb2.WalEntry.FromString,
                _registered_method=True)
        self.ExplainQuery = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/ExplainQuery',
                request_serializer=polargraph__pb2.QueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.ExplainResponse.FromString,
                _registered_method=True)
        self.MigrateSchema = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/MigrateSchema',
                request_serializer=polargraph__pb2.MigrateRequest.SerializeToString,
                response_deserializer=polargraph__pb2.MigrateResponse.FromString,
                _registered_method=True)
        self.MigrationStatus = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/MigrationStatus',
                request_serializer=polargraph__pb2.MigrationStatusRequest.SerializeToString,
                response_deserializer=polargraph__pb2.MigrationStatusResponse.FromString,
                _registered_method=True)
        self.CypherQuery = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/CypherQuery',
                request_serializer=polargraph__pb2.CypherQueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.CypherQueryResponse.FromString,
                _registered_method=True)
        self.CypherWrite = channel.unary_unary(
                '/polargraph.v1.PolarGraphService/CypherWrite',
                request_serializer=polargraph__pb2.CypherWriteRequest.SerializeToString,
                response_deserializer=polargraph__pb2.CypherWriteResponse.FromString,
                _registered_method=True)
        self.QueryStream = channel.unary_stream(
                '/polargraph.v1.PolarGraphService/QueryStream',
                request_serializer=polargraph__pb2.QueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.QueryStreamChunk.FromString,
                _registered_method=True)
        self.CypherQueryStream = channel.unary_stream(
                '/polargraph.v1.PolarGraphService/CypherQueryStream',
                request_serializer=polargraph__pb2.CypherQueryRequest.SerializeToString,
                response_deserializer=polargraph__pb2.QueryStreamChunk.FromString,
                _registered_method=True)


class PolarGraphServiceServicer:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    def Insert(self, request, context):
        """/ Insert one or more triples in a single atomic transaction.
        / Returns ABORTED if a write-write conflict is detected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """/ Execute a conjunctive query and return all satisfying variable bindings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertVector(self, request, context):
        """/ Insert or update a node's embedding vector in the HNSW index.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVector(self, request, context):
        """/ Search for the k nearest neighbors of a query vector.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reachable(self, request, context):
        """/ Return all nodes transitively reachable from `start` via `predicate`.
        / max_hops = 0 means unlimited depth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNodeType(self, request, context):
        """/ Register (or overwrite) a node type schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeType(self, request, context):
        """/ Look up a registered node type by name. Returns an empty definition if
        / the type does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodeTypes(self, request, context):
        """/ Return all registered node type schemas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateNode(self, request, context):
        """/ Validate a property map against a registered schema.
        / Returns valid=false and a list of error messages on failure.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEdgeType(self, request, context):
        """/ Register (or overwrite) an edge type schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEdgeType(self, request, context):
        """/ Look up a registered edge type by predicate name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEdgeTypes(self, request, context):
        """/ Return all registered edge type schemas.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateEdge(self, request, context):
        """/ Validate an edge's endpoint types and property map against a schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPredicatesBetween(self, request, context):
        """/ Return all registered predicate names whose domain and range match
        / the supplied node type names. Unconstrained slots match any type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectorFiltered(self, request, context):
        """/ Vector search with a node-type or reachability filter.
        / Runs HNSW with a large candidate pool then post-filters to the allowed set.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVectorInSet(self, request, context):
        """/ Score an explicit set of node IDs against a query vector; return top-k.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertVectors(self, request, context):
        """/ Insert multiple vectors into a named space atomically.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSeedQuery(self, request, context):
        """/ Run an ANN vector search and use the results as seed bindings for a
        / conjunctive Datalog query. Returns scored binding rows that satisfy
        / both the vector similarity criterion and all graph patterns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBackup(self, request, context):
        """/ Create a new incremental backup of the live store.
        / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBackups(self, request, context):
        """/ List all available backups with ID, timestamp, size, and file count.
        / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeOldBackups(self, request, context):
        """/ Delete all but the keep_n most recent backups.
        / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
        / Note: restore is an offline operation — see docs/architecture.md.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunRetention(self, request, context):
        """/ Scan all hexastore column families and delete triples whose
        / transaction time or valid-time window has expired per the supplied policy.
        / Triggers a full RocksDB compaction on any CF that had deletions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaStatus(self, request, context):
        """/ Return replication status for this server instance.
        / `is_replica` is false and all other fields are zero/empty on the primary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWal(self, request, context):
        """/ Stream WAL entries from the primary. Returns FAILED_PRECONDITION on a replica.
        / The stream runs indefinitely until the client disconnects; new entries are
        / delivered within ~50 ms of commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainQuery(self, request, context):
        """/ Return the static execution plan for a query without running it.
        / No database access is performed — pure static analysis of index selection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateSchema(self, request, context):
        """/ Apply any pending schema migrations and return the list of versions run.
        / When dry_run is true, reports what would be applied without making changes.
        / Returns FAILED_PRECONDITION on a read replica.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrationStatus(self, request, context):
        """/ Return the current and latest migration version, plus the full history
        / of applied migrations with timestamps.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CypherQuery(self, request, context):
        """/ Parse and execute a Cypher query string. Supports a subset of openCypher:
        / MATCH, WHERE (= only), RETURN, LIMIT; directed relationships; transitive
        / closure with [:pred*] or [:pred*min..max].
        / Returns INVALID_ARGUMENT if the Cypher string cannot be parsed or contains
        / write clauses (CREATE/MERGE/SET/DELETE) — use CypherWrite for mutations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CypherWrite(self, request, context):
        """/ Parse and execute a Cypher write statement (CREATE, MERGE, SET, DELETE).
        / Executes atomically in a single MVCC transaction.
        / Returns INVALID_ARGUMENT if the statement cannot be parsed or contains no
        / write clause. Returns FAILED_PRECONDITION on a read replica.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryStream(self, request, context):
        """/ Like `Query` but streams results in chunks of up to 500 bindings each.
        / Use for large result sets that would otherwise exceed memory or message-size
        / limits. The final chunk has `done = true`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CypherQueryStream(self, request, context):
        """/ Like `CypherQuery` but streams results in chunks. Respects the LIMIT clause
        / in the Cypher string. The final chunk has `done = true`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolarGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=polargraph__pb2.InsertRequest.FromString,
                    response_serializer=polargraph__pb2.InsertResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=polargraph__pb2.QueryRequest.FromString,
                    response_serializer=polargraph__pb2.QueryResponse.SerializeToString,
            ),
            'InsertVector': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertVector,
                    request_deserializer=polargraph__pb2.InsertVectorRequest.FromString,
                    response_serializer=polargraph__pb2.InsertVectorResponse.SerializeToString,
            ),
            'SearchVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVector,
                    request_deserializer=polargraph__pb2.SearchVectorRequest.FromString,
                    response_serializer=polargraph__pb2.SearchVectorResponse.SerializeToString,
            ),
            'Reachable': grpc.unary_unary_rpc_method_handler(
                    servicer.Reachable,
                    request_deserializer=polargraph__pb2.ReachableRequest.FromString,
                    response_serializer=polargraph__pb2.ReachableResponse.SerializeToString,
            ),
            'RegisterNodeType': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNodeType,
                    request_deserializer=polargraph__pb2.RegisterNodeTypeRequest.FromString,
                    response_serializer=polargraph__pb2.RegisterNodeTypeResponse.SerializeToString,
            ),
            'GetNodeType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeType,
                    request_deserializer=polargraph__pb2.GetNodeTypeRequest.FromString,
                    response_serializer=polargraph__pb2.GetNodeTypeResponse.SerializeToString,
            ),
            'ListNodeTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodeTypes,
                    request_deserializer=polargraph__pb2.ListNodeTypesRequest.FromString,
                    response_serializer=polargraph__pb2.ListNodeTypesResponse.SerializeToString,
            ),
            'ValidateNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateNode,
                    request_deserializer=polargraph__pb2.ValidateNodeRequest.FromString,
                    response_serializer=polargraph__pb2.ValidateNodeResponse.SerializeToString,
            ),
            'RegisterEdgeType': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEdgeType,
                    request_deserializer=polargraph__pb2.RegisterEdgeTypeRequest.FromString,
                    response_serializer=polargraph__pb2.RegisterEdgeTypeResponse.SerializeToString,
            ),
            'GetEdgeType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEdgeType,
                    request_deserializer=polargraph__pb2.GetEdgeTypeRequest.FromString,
                    response_serializer=polargraph__pb2.GetEdgeTypeResponse.SerializeToString,
            ),
            'ListEdgeTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEdgeTypes,
                    request_deserializer=polargraph__pb2.ListEdgeTypesRequest.FromString,
                    response_serializer=polargraph__pb2.ListEdgeTypesResponse.SerializeToString,
            ),
            'ValidateEdge': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateEdge,
                    request_deserializer=polargraph__pb2.ValidateEdgeRequest.FromString,
                    response_serializer=polargraph__pb2.ValidateEdgeResponse.SerializeToString,
            ),
            'ListPredicatesBetween': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPredicatesBetween,
                    request_deserializer=polargraph__pb2.ListPredicatesBetweenRequest.FromString,
                    response_serializer=polargraph__pb2.ListPredicatesBetweenResponse.SerializeToString,
            ),
            'SearchVectorFiltered': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectorFiltered,
                    request_deserializer=polargraph__pb2.SearchVectorFilteredRequest.FromString,
                    response_serializer=polargraph__pb2.SearchVectorFilteredResponse.SerializeToString,
            ),
            'SearchVectorInSet': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVectorInSet,
                    request_deserializer=polargraph__pb2.SearchVectorInSetRequest.FromString,
                    response_serializer=polargraph__pb2.SearchVectorInSetResponse.SerializeToString,
            ),
            'BatchInsertVectors': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertVectors,
                    request_deserializer=polargraph__pb2.BatchInsertVectorsRequest.FromString,
                    response_serializer=polargraph__pb2.BatchInsertVectorsResponse.SerializeToString,
            ),
            'VectorSeedQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.VectorSeedQuery,
                    request_deserializer=polargraph__pb2.VectorSeedQueryRequest.FromString,
                    response_serializer=polargraph__pb2.VectorSeedQueryResponse.SerializeToString,
            ),
            'CreateBackup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBackup,
                    request_deserializer=polargraph__pb2.CreateBackupRequest.FromString,
                    response_serializer=polargraph__pb2.CreateBackupResponse.SerializeToString,
            ),
            'ListBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackups,
                    request_deserializer=polargraph__pb2.ListBackupsRequest.FromString,
                    response_serializer=polargraph__pb2.ListBackupsResponse.SerializeToString,
            ),
            'PurgeOldBackups': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeOldBackups,
                    request_deserializer=polargraph__pb2.PurgeOldBackupsRequest.FromString,
                    response_serializer=polargraph__pb2.PurgeOldBackupsResponse.SerializeToString,
            ),
            'RunRetention': grpc.unary_unary_rpc_method_handler(
                    servicer.RunRetention,
                    request_deserializer=polargraph__pb2.RunRetentionRequest.FromString,
                    response_serializer=polargraph__pb2.RunRetentionResponse.SerializeToString,
            ),
            'ReplicaStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaStatus,
                    request_deserializer=polargraph__pb2.ReplicaStatusRequest.FromString,
                    response_serializer=polargraph__pb2.ReplicaStatusResponse.SerializeToString,
            ),
            'StreamWal': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWal,
                    request_deserializer=polargraph__pb2.StreamWalRequest.FromString,
                    response_serializer=polargraph__pb2.WalEntry.SerializeToString,
            ),
            'ExplainQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainQuery,
                    request_deserializer=polargraph__pb2.QueryRequest.FromString,
                    response_serializer=polargraph__pb2.ExplainResponse.SerializeToString,
            ),
            'MigrateSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateSchema,
                    request_deserializer=polargraph__pb2.MigrateRequest.FromString,
                    response_serializer=polargraph__pb2.MigrateResponse.SerializeToString,
            ),
            'MigrationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrationStatus,
                    request_deserializer=polargraph__pb2.MigrationStatusRequest.FromString,
                    response_serializer=polargraph__pb2.MigrationStatusResponse.SerializeToString,
            ),
            'CypherQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.CypherQuery,
                    request_deserializer=polargraph__pb2.CypherQueryRequest.FromString,
                    response_serializer=polargraph__pb2.CypherQueryResponse.SerializeToString,
            ),
            'CypherWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.CypherWrite,
                    request_deserializer=polargraph__pb2.CypherWriteRequest.FromString,
                    response_serializer=polargraph__pb2.CypherWriteResponse.SerializeToString,
            ),
            'QueryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryStream,
                    request_deserializer=polargraph__pb2.QueryRequest.FromString,
                    response_serializer=polargraph__pb2.QueryStreamChunk.SerializeToString,
            ),
            'CypherQueryStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CypherQueryStream,
                    request_deserializer=polargraph__pb2.CypherQueryRequest.FromString,
                    response_serializer=polargraph__pb2.QueryStreamChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polargraph.v1.PolarGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('polargraph.v1.PolarGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolarGraphService:
    """── Service ───────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/Insert',
            polargraph__pb2.InsertRequest.SerializeToString,
            polargraph__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/Query',
            polargraph__pb2.QueryRequest.SerializeToString,
            polargraph__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/InsertVector',
            polargraph__pb2.InsertVectorRequest.SerializeToString,
            polargraph__pb2.InsertVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/SearchVector',
            polargraph__pb2.SearchVectorRequest.SerializeToString,
            polargraph__pb2.SearchVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reachable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/Reachable',
            polargraph__pb2.ReachableRequest.SerializeToString,
            polargraph__pb2.ReachableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNodeType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/RegisterNodeType',
            polargraph__pb2.RegisterNodeTypeRequest.SerializeToString,
            polargraph__pb2.RegisterNodeTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/GetNodeType',
            polargraph__pb2.GetNodeTypeRequest.SerializeToString,
            polargraph__pb2.GetNodeTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodeTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ListNodeTypes',
            polargraph__pb2.ListNodeTypesRequest.SerializeToString,
            polargraph__pb2.ListNodeTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ValidateNode',
            polargraph__pb2.ValidateNodeRequest.SerializeToString,
            polargraph__pb2.ValidateNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEdgeType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/RegisterEdgeType',
            polargraph__pb2.RegisterEdgeTypeRequest.SerializeToString,
            polargraph__pb2.RegisterEdgeTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEdgeType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/GetEdgeType',
            polargraph__pb2.GetEdgeTypeRequest.SerializeToString,
            polargraph__pb2.GetEdgeTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEdgeTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ListEdgeTypes',
            polargraph__pb2.ListEdgeTypesRequest.SerializeToString,
            polargraph__pb2.ListEdgeTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateEdge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ValidateEdge',
            polargraph__pb2.ValidateEdgeRequest.SerializeToString,
            polargraph__pb2.ValidateEdgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPredicatesBetween(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ListPredicatesBetween',
            polargraph__pb2.ListPredicatesBetweenRequest.SerializeToString,
            polargraph__pb2.ListPredicatesBetweenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectorFiltered(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/SearchVectorFiltered',
            polargraph__pb2.SearchVectorFilteredRequest.SerializeToString,
            polargraph__pb2.SearchVectorFilteredResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchVectorInSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/SearchVectorInSet',
            polargraph__pb2.SearchVectorInSetRequest.SerializeToString,
            polargraph__pb2.SearchVectorInSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertVectors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/BatchInsertVectors',
            polargraph__pb2.BatchInsertVectorsRequest.SerializeToString,
            polargraph__pb2.BatchInsertVectorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSeedQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/VectorSeedQuery',
            polargraph__pb2.VectorSeedQueryRequest.SerializeToString,
            polargraph__pb2.VectorSeedQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBackup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/CreateBackup',
            polargraph__pb2.CreateBackupRequest.SerializeToString,
            polargraph__pb2.CreateBackupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ListBackups',
            polargraph__pb2.ListBackupsRequest.SerializeToString,
            polargraph__pb2.ListBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeOldBackups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/PurgeOldBackups',
            polargraph__pb2.PurgeOldBackupsRequest.SerializeToString,
            polargraph__pb2.PurgeOldBackupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunRetention(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/RunRetention',
            polargraph__pb2.RunRetentionRequest.SerializeToString,
            polargraph__pb2.RunRetentionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicaStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ReplicaStatus',
            polargraph__pb2.ReplicaStatusRequest.SerializeToString,
            polargraph__pb2.ReplicaStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polargraph.v1.PolarGraphService/StreamWal',
            polargraph__pb2.StreamWalRequest.SerializeToString,
            polargraph__pb2.WalEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/ExplainQuery',
            polargraph__pb2.QueryRequest.SerializeToString,
            polargraph__pb2.ExplainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/MigrateSchema',
            polargraph__pb2.MigrateRequest.SerializeToString,
            polargraph__pb2.MigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/MigrationStatus',
            polargraph__pb2.MigrationStatusRequest.SerializeToString,
            polargraph__pb2.MigrationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CypherQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/CypherQuery',
            polargraph__pb2.CypherQueryRequest.SerializeToString,
            polargraph__pb2.CypherQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CypherWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/polargraph.v1.PolarGraphService/CypherWrite',
            polargraph__pb2.CypherWriteRequest.SerializeToString,
            polargraph__pb2.CypherWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polargraph.v1.PolarGraphService/QueryStream',
            polargraph__pb2.QueryRequest.SerializeToString,
            polargraph__pb2.QueryStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CypherQueryStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/polargraph.v1.PolarGraphService/CypherQueryStream',
            polargraph__pb2.CypherQueryRequest.SerializeToString,
            polargraph__pb2.QueryStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
