// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: polargraph.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolarGraphService_Insert_FullMethodName                = "/polargraph.v1.PolarGraphService/Insert"
	PolarGraphService_Query_FullMethodName                 = "/polargraph.v1.PolarGraphService/Query"
	PolarGraphService_InsertVector_FullMethodName          = "/polargraph.v1.PolarGraphService/InsertVector"
	PolarGraphService_SearchVector_FullMethodName          = "/polargraph.v1.PolarGraphService/SearchVector"
	PolarGraphService_Reachable_FullMethodName             = "/polargraph.v1.PolarGraphService/Reachable"
	PolarGraphService_RegisterNodeType_FullMethodName      = "/polargraph.v1.PolarGraphService/RegisterNodeType"
	PolarGraphService_GetNodeType_FullMethodName           = "/polargraph.v1.PolarGraphService/GetNodeType"
	PolarGraphService_ListNodeTypes_FullMethodName         = "/polargraph.v1.PolarGraphService/ListNodeTypes"
	PolarGraphService_ValidateNode_FullMethodName          = "/polargraph.v1.PolarGraphService/ValidateNode"
	PolarGraphService_RegisterEdgeType_FullMethodName      = "/polargraph.v1.PolarGraphService/RegisterEdgeType"
	PolarGraphService_GetEdgeType_FullMethodName           = "/polargraph.v1.PolarGraphService/GetEdgeType"
	PolarGraphService_ListEdgeTypes_FullMethodName         = "/polargraph.v1.PolarGraphService/ListEdgeTypes"
	PolarGraphService_ValidateEdge_FullMethodName          = "/polargraph.v1.PolarGraphService/ValidateEdge"
	PolarGraphService_ListPredicatesBetween_FullMethodName = "/polargraph.v1.PolarGraphService/ListPredicatesBetween"
	PolarGraphService_SearchVectorFiltered_FullMethodName  = "/polargraph.v1.PolarGraphService/SearchVectorFiltered"
	PolarGraphService_SearchVectorInSet_FullMethodName     = "/polargraph.v1.PolarGraphService/SearchVectorInSet"
	PolarGraphService_BatchInsertVectors_FullMethodName    = "/polargraph.v1.PolarGraphService/BatchInsertVectors"
	PolarGraphService_VectorSeedQuery_FullMethodName       = "/polargraph.v1.PolarGraphService/VectorSeedQuery"
	PolarGraphService_CreateBackup_FullMethodName          = "/polargraph.v1.PolarGraphService/CreateBackup"
	PolarGraphService_ListBackups_FullMethodName           = "/polargraph.v1.PolarGraphService/ListBackups"
	PolarGraphService_PurgeOldBackups_FullMethodName       = "/polargraph.v1.PolarGraphService/PurgeOldBackups"
	PolarGraphService_RunRetention_FullMethodName          = "/polargraph.v1.PolarGraphService/RunRetention"
	PolarGraphService_ReplicaStatus_FullMethodName         = "/polargraph.v1.PolarGraphService/ReplicaStatus"
	PolarGraphService_StreamWal_FullMethodName             = "/polargraph.v1.PolarGraphService/StreamWal"
	PolarGraphService_ExplainQuery_FullMethodName          = "/polargraph.v1.PolarGraphService/ExplainQuery"
	PolarGraphService_MigrateSchema_FullMethodName         = "/polargraph.v1.PolarGraphService/MigrateSchema"
	PolarGraphService_MigrationStatus_FullMethodName       = "/polargraph.v1.PolarGraphService/MigrationStatus"
	PolarGraphService_CypherQuery_FullMethodName           = "/polargraph.v1.PolarGraphService/CypherQuery"
	PolarGraphService_CypherWrite_FullMethodName           = "/polargraph.v1.PolarGraphService/CypherWrite"
	PolarGraphService_QueryStream_FullMethodName           = "/polargraph.v1.PolarGraphService/QueryStream"
	PolarGraphService_CypherQueryStream_FullMethodName     = "/polargraph.v1.PolarGraphService/CypherQueryStream"
)

// PolarGraphServiceClient is the client API for PolarGraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolarGraphServiceClient interface {
	// / Insert one or more triples in a single atomic transaction.
	// / Returns ABORTED if a write-write conflict is detected.
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// / Execute a conjunctive query and return all satisfying variable bindings.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// / Insert or update a node's embedding vector in the HNSW index.
	InsertVector(ctx context.Context, in *InsertVectorRequest, opts ...grpc.CallOption) (*InsertVectorResponse, error)
	// / Search for the k nearest neighbors of a query vector.
	SearchVector(ctx context.Context, in *SearchVectorRequest, opts ...grpc.CallOption) (*SearchVectorResponse, error)
	// / Return all nodes transitively reachable from `start` via `predicate`.
	// / max_hops = 0 means unlimited depth.
	Reachable(ctx context.Context, in *ReachableRequest, opts ...grpc.CallOption) (*ReachableResponse, error)
	// / Register (or overwrite) a node type schema.
	RegisterNodeType(ctx context.Context, in *RegisterNodeTypeRequest, opts ...grpc.CallOption) (*RegisterNodeTypeResponse, error)
	// / Look up a registered node type by name. Returns an empty definition if
	// / the type does not exist.
	GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*GetNodeTypeResponse, error)
	// / Return all registered node type schemas.
	ListNodeTypes(ctx context.Context, in *ListNodeTypesRequest, opts ...grpc.CallOption) (*ListNodeTypesResponse, error)
	// / Validate a property map against a registered schema.
	// / Returns valid=false and a list of error messages on failure.
	ValidateNode(ctx context.Context, in *ValidateNodeRequest, opts ...grpc.CallOption) (*ValidateNodeResponse, error)
	// / Register (or overwrite) an edge type schema.
	RegisterEdgeType(ctx context.Context, in *RegisterEdgeTypeRequest, opts ...grpc.CallOption) (*RegisterEdgeTypeResponse, error)
	// / Look up a registered edge type by predicate name.
	GetEdgeType(ctx context.Context, in *GetEdgeTypeRequest, opts ...grpc.CallOption) (*GetEdgeTypeResponse, error)
	// / Return all registered edge type schemas.
	ListEdgeTypes(ctx context.Context, in *ListEdgeTypesRequest, opts ...grpc.CallOption) (*ListEdgeTypesResponse, error)
	// / Validate an edge's endpoint types and property map against a schema.
	ValidateEdge(ctx context.Context, in *ValidateEdgeRequest, opts ...grpc.CallOption) (*ValidateEdgeResponse, error)
	// / Return all registered predicate names whose domain and range match
	// / the supplied node type names. Unconstrained slots match any type.
	ListPredicatesBetween(ctx context.Context, in *ListPredicatesBetweenRequest, opts ...grpc.CallOption) (*ListPredicatesBetweenResponse, error)
	// / Vector search with a node-type or reachability filter.
	// / Runs HNSW with a large candidate pool then post-filters to the allowed set.
	SearchVectorFiltered(ctx context.Context, in *SearchVectorFilteredRequest, opts ...grpc.CallOption) (*SearchVectorFilteredResponse, error)
	// / Score an explicit set of node IDs against a query vector; return top-k.
	SearchVectorInSet(ctx context.Context, in *SearchVectorInSetRequest, opts ...grpc.CallOption) (*SearchVectorInSetResponse, error)
	// / Insert multiple vectors into a named space atomically.
	BatchInsertVectors(ctx context.Context, in *BatchInsertVectorsRequest, opts ...grpc.CallOption) (*BatchInsertVectorsResponse, error)
	// / Run an ANN vector search and use the results as seed bindings for a
	// / conjunctive Datalog query. Returns scored binding rows that satisfy
	// / both the vector similarity criterion and all graph patterns.
	VectorSeedQuery(ctx context.Context, in *VectorSeedQueryRequest, opts ...grpc.CallOption) (*VectorSeedQueryResponse, error)
	// / Create a new incremental backup of the live store.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error)
	// / List all available backups with ID, timestamp, size, and file count.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	// / Delete all but the keep_n most recent backups.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	// / Note: restore is an offline operation — see docs/architecture.md.
	PurgeOldBackups(ctx context.Context, in *PurgeOldBackupsRequest, opts ...grpc.CallOption) (*PurgeOldBackupsResponse, error)
	// / Scan all hexastore column families and delete triples whose
	// / transaction time or valid-time window has expired per the supplied policy.
	// / Triggers a full RocksDB compaction on any CF that had deletions.
	RunRetention(ctx context.Context, in *RunRetentionRequest, opts ...grpc.CallOption) (*RunRetentionResponse, error)
	// / Return replication status for this server instance.
	// / `is_replica` is false and all other fields are zero/empty on the primary.
	ReplicaStatus(ctx context.Context, in *ReplicaStatusRequest, opts ...grpc.CallOption) (*ReplicaStatusResponse, error)
	// / Stream WAL entries from the primary. Returns FAILED_PRECONDITION on a replica.
	// / The stream runs indefinitely until the client disconnects; new entries are
	// / delivered within ~50 ms of commit.
	StreamWal(ctx context.Context, in *StreamWalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WalEntry], error)
	// / Return the static execution plan for a query without running it.
	// / No database access is performed — pure static analysis of index selection.
	ExplainQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	// / Apply any pending schema migrations and return the list of versions run.
	// / When dry_run is true, reports what would be applied without making changes.
	// / Returns FAILED_PRECONDITION on a read replica.
	MigrateSchema(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error)
	// / Return the current and latest migration version, plus the full history
	// / of applied migrations with timestamps.
	MigrationStatus(ctx context.Context, in *MigrationStatusRequest, opts ...grpc.CallOption) (*MigrationStatusResponse, error)
	// / Parse and execute a Cypher query string. Supports a subset of openCypher:
	// / MATCH, WHERE (= only), RETURN, LIMIT; directed relationships; transitive
	// / closure with [:pred*] or [:pred*min..max].
	// / Returns INVALID_ARGUMENT if the Cypher string cannot be parsed or contains
	// / write clauses (CREATE/MERGE/SET/DELETE) — use CypherWrite for mutations.
	CypherQuery(ctx context.Context, in *CypherQueryRequest, opts ...grpc.CallOption) (*CypherQueryResponse, error)
	// / Parse and execute a Cypher write statement (CREATE, MERGE, SET, DELETE).
	// / Executes atomically in a single MVCC transaction.
	// / Returns INVALID_ARGUMENT if the statement cannot be parsed or contains no
	// / write clause. Returns FAILED_PRECONDITION on a read replica.
	CypherWrite(ctx context.Context, in *CypherWriteRequest, opts ...grpc.CallOption) (*CypherWriteResponse, error)
	// / Like `Query` but streams results in chunks of up to 500 bindings each.
	// / Use for large result sets that would otherwise exceed memory or message-size
	// / limits. The final chunk has `done = true`.
	QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamChunk], error)
	// / Like `CypherQuery` but streams results in chunks. Respects the LIMIT clause
	// / in the Cypher string. The final chunk has `done = true`.
	CypherQueryStream(ctx context.Context, in *CypherQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamChunk], error)
}

type polarGraphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolarGraphServiceClient(cc grpc.ClientConnInterface) PolarGraphServiceClient {
	return &polarGraphServiceClient{cc}
}

func (c *polarGraphServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) InsertVector(ctx context.Context, in *InsertVectorRequest, opts ...grpc.CallOption) (*InsertVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertVectorResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_InsertVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) SearchVector(ctx context.Context, in *SearchVectorRequest, opts ...grpc.CallOption) (*SearchVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVectorResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_SearchVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) Reachable(ctx context.Context, in *ReachableRequest, opts ...grpc.CallOption) (*ReachableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReachableResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_Reachable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) RegisterNodeType(ctx context.Context, in *RegisterNodeTypeRequest, opts ...grpc.CallOption) (*RegisterNodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeTypeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_RegisterNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) GetNodeType(ctx context.Context, in *GetNodeTypeRequest, opts ...grpc.CallOption) (*GetNodeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeTypeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_GetNodeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ListNodeTypes(ctx context.Context, in *ListNodeTypesRequest, opts ...grpc.CallOption) (*ListNodeTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodeTypesResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ListNodeTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ValidateNode(ctx context.Context, in *ValidateNodeRequest, opts ...grpc.CallOption) (*ValidateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateNodeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ValidateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) RegisterEdgeType(ctx context.Context, in *RegisterEdgeTypeRequest, opts ...grpc.CallOption) (*RegisterEdgeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEdgeTypeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_RegisterEdgeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) GetEdgeType(ctx context.Context, in *GetEdgeTypeRequest, opts ...grpc.CallOption) (*GetEdgeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEdgeTypeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_GetEdgeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ListEdgeTypes(ctx context.Context, in *ListEdgeTypesRequest, opts ...grpc.CallOption) (*ListEdgeTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEdgeTypesResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ListEdgeTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ValidateEdge(ctx context.Context, in *ValidateEdgeRequest, opts ...grpc.CallOption) (*ValidateEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateEdgeResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ValidateEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ListPredicatesBetween(ctx context.Context, in *ListPredicatesBetweenRequest, opts ...grpc.CallOption) (*ListPredicatesBetweenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPredicatesBetweenResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ListPredicatesBetween_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) SearchVectorFiltered(ctx context.Context, in *SearchVectorFilteredRequest, opts ...grpc.CallOption) (*SearchVectorFilteredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVectorFilteredResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_SearchVectorFiltered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) SearchVectorInSet(ctx context.Context, in *SearchVectorInSetRequest, opts ...grpc.CallOption) (*SearchVectorInSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchVectorInSetResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_SearchVectorInSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) BatchInsertVectors(ctx context.Context, in *BatchInsertVectorsRequest, opts ...grpc.CallOption) (*BatchInsertVectorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertVectorsResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_BatchInsertVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) VectorSeedQuery(ctx context.Context, in *VectorSeedQueryRequest, opts ...grpc.CallOption) (*VectorSeedQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSeedQueryResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_VectorSeedQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*CreateBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBackupResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) PurgeOldBackups(ctx context.Context, in *PurgeOldBackupsRequest, opts ...grpc.CallOption) (*PurgeOldBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeOldBackupsResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_PurgeOldBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) RunRetention(ctx context.Context, in *RunRetentionRequest, opts ...grpc.CallOption) (*RunRetentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRetentionResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_RunRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) ReplicaStatus(ctx context.Context, in *ReplicaStatusRequest, opts ...grpc.CallOption) (*ReplicaStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplicaStatusResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ReplicaStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) StreamWal(ctx context.Context, in *StreamWalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WalEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolarGraphService_ServiceDesc.Streams[0], PolarGraphService_StreamWal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWalRequest, WalEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_StreamWalClient = grpc.ServerStreamingClient[WalEntry]

func (c *polarGraphServiceClient) ExplainQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_ExplainQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) MigrateSchema(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_MigrateSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) MigrationStatus(ctx context.Context, in *MigrationStatusRequest, opts ...grpc.CallOption) (*MigrationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationStatusResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_MigrationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) CypherQuery(ctx context.Context, in *CypherQueryRequest, opts ...grpc.CallOption) (*CypherQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CypherQueryResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_CypherQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) CypherWrite(ctx context.Context, in *CypherWriteRequest, opts ...grpc.CallOption) (*CypherWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CypherWriteResponse)
	err := c.cc.Invoke(ctx, PolarGraphService_CypherWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *polarGraphServiceClient) QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolarGraphService_ServiceDesc.Streams[1], PolarGraphService_QueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_QueryStreamClient = grpc.ServerStreamingClient[QueryStreamChunk]

func (c *polarGraphServiceClient) CypherQueryStream(ctx context.Context, in *CypherQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryStreamChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolarGraphService_ServiceDesc.Streams[2], PolarGraphService_CypherQueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CypherQueryRequest, QueryStreamChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_CypherQueryStreamClient = grpc.ServerStreamingClient[QueryStreamChunk]

// PolarGraphServiceServer is the server API for PolarGraphService service.
// All implementations must embed UnimplementedPolarGraphServiceServer
// for forward compatibility.
type PolarGraphServiceServer interface {
	// / Insert one or more triples in a single atomic transaction.
	// / Returns ABORTED if a write-write conflict is detected.
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// / Execute a conjunctive query and return all satisfying variable bindings.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// / Insert or update a node's embedding vector in the HNSW index.
	InsertVector(context.Context, *InsertVectorRequest) (*InsertVectorResponse, error)
	// / Search for the k nearest neighbors of a query vector.
	SearchVector(context.Context, *SearchVectorRequest) (*SearchVectorResponse, error)
	// / Return all nodes transitively reachable from `start` via `predicate`.
	// / max_hops = 0 means unlimited depth.
	Reachable(context.Context, *ReachableRequest) (*ReachableResponse, error)
	// / Register (or overwrite) a node type schema.
	RegisterNodeType(context.Context, *RegisterNodeTypeRequest) (*RegisterNodeTypeResponse, error)
	// / Look up a registered node type by name. Returns an empty definition if
	// / the type does not exist.
	GetNodeType(context.Context, *GetNodeTypeRequest) (*GetNodeTypeResponse, error)
	// / Return all registered node type schemas.
	ListNodeTypes(context.Context, *ListNodeTypesRequest) (*ListNodeTypesResponse, error)
	// / Validate a property map against a registered schema.
	// / Returns valid=false and a list of error messages on failure.
	ValidateNode(context.Context, *ValidateNodeRequest) (*ValidateNodeResponse, error)
	// / Register (or overwrite) an edge type schema.
	RegisterEdgeType(context.Context, *RegisterEdgeTypeRequest) (*RegisterEdgeTypeResponse, error)
	// / Look up a registered edge type by predicate name.
	GetEdgeType(context.Context, *GetEdgeTypeRequest) (*GetEdgeTypeResponse, error)
	// / Return all registered edge type schemas.
	ListEdgeTypes(context.Context, *ListEdgeTypesRequest) (*ListEdgeTypesResponse, error)
	// / Validate an edge's endpoint types and property map against a schema.
	ValidateEdge(context.Context, *ValidateEdgeRequest) (*ValidateEdgeResponse, error)
	// / Return all registered predicate names whose domain and range match
	// / the supplied node type names. Unconstrained slots match any type.
	ListPredicatesBetween(context.Context, *ListPredicatesBetweenRequest) (*ListPredicatesBetweenResponse, error)
	// / Vector search with a node-type or reachability filter.
	// / Runs HNSW with a large candidate pool then post-filters to the allowed set.
	SearchVectorFiltered(context.Context, *SearchVectorFilteredRequest) (*SearchVectorFilteredResponse, error)
	// / Score an explicit set of node IDs against a query vector; return top-k.
	SearchVectorInSet(context.Context, *SearchVectorInSetRequest) (*SearchVectorInSetResponse, error)
	// / Insert multiple vectors into a named space atomically.
	BatchInsertVectors(context.Context, *BatchInsertVectorsRequest) (*BatchInsertVectorsResponse, error)
	// / Run an ANN vector search and use the results as seed bindings for a
	// / conjunctive Datalog query. Returns scored binding rows that satisfy
	// / both the vector similarity criterion and all graph patterns.
	VectorSeedQuery(context.Context, *VectorSeedQueryRequest) (*VectorSeedQueryResponse, error)
	// / Create a new incremental backup of the live store.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error)
	// / List all available backups with ID, timestamp, size, and file count.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	// / Delete all but the keep_n most recent backups.
	// / Returns FAILED_PRECONDITION if the server was not started with --backup-dir.
	// / Note: restore is an offline operation — see docs/architecture.md.
	PurgeOldBackups(context.Context, *PurgeOldBackupsRequest) (*PurgeOldBackupsResponse, error)
	// / Scan all hexastore column families and delete triples whose
	// / transaction time or valid-time window has expired per the supplied policy.
	// / Triggers a full RocksDB compaction on any CF that had deletions.
	RunRetention(context.Context, *RunRetentionRequest) (*RunRetentionResponse, error)
	// / Return replication status for this server instance.
	// / `is_replica` is false and all other fields are zero/empty on the primary.
	ReplicaStatus(context.Context, *ReplicaStatusRequest) (*ReplicaStatusResponse, error)
	// / Stream WAL entries from the primary. Returns FAILED_PRECONDITION on a replica.
	// / The stream runs indefinitely until the client disconnects; new entries are
	// / delivered within ~50 ms of commit.
	StreamWal(*StreamWalRequest, grpc.ServerStreamingServer[WalEntry]) error
	// / Return the static execution plan for a query without running it.
	// / No database access is performed — pure static analysis of index selection.
	ExplainQuery(context.Context, *QueryRequest) (*ExplainResponse, error)
	// / Apply any pending schema migrations and return the list of versions run.
	// / When dry_run is true, reports what would be applied without making changes.
	// / Returns FAILED_PRECONDITION on a read replica.
	MigrateSchema(context.Context, *MigrateRequest) (*MigrateResponse, error)
	// / Return the current and latest migration version, plus the full history
	// / of applied migrations with timestamps.
	MigrationStatus(context.Context, *MigrationStatusRequest) (*MigrationStatusResponse, error)
	// / Parse and execute a Cypher query string. Supports a subset of openCypher:
	// / MATCH, WHERE (= only), RETURN, LIMIT; directed relationships; transitive
	// / closure with [:pred*] or [:pred*min..max].
	// / Returns INVALID_ARGUMENT if the Cypher string cannot be parsed or contains
	// / write clauses (CREATE/MERGE/SET/DELETE) — use CypherWrite for mutations.
	CypherQuery(context.Context, *CypherQueryRequest) (*CypherQueryResponse, error)
	// / Parse and execute a Cypher write statement (CREATE, MERGE, SET, DELETE).
	// / Executes atomically in a single MVCC transaction.
	// / Returns INVALID_ARGUMENT if the statement cannot be parsed or contains no
	// / write clause. Returns FAILED_PRECONDITION on a read replica.
	CypherWrite(context.Context, *CypherWriteRequest) (*CypherWriteResponse, error)
	// / Like `Query` but streams results in chunks of up to 500 bindings each.
	// / Use for large result sets that would otherwise exceed memory or message-size
	// / limits. The final chunk has `done = true`.
	QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryStreamChunk]) error
	// / Like `CypherQuery` but streams results in chunks. Respects the LIMIT clause
	// / in the Cypher string. The final chunk has `done = true`.
	CypherQueryStream(*CypherQueryRequest, grpc.ServerStreamingServer[QueryStreamChunk]) error
	mustEmbedUnimplementedPolarGraphServiceServer()
}

// UnimplementedPolarGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolarGraphServiceServer struct{}

func (UnimplementedPolarGraphServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedPolarGraphServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedPolarGraphServiceServer) InsertVector(context.Context, *InsertVectorRequest) (*InsertVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertVector not implemented")
}
func (UnimplementedPolarGraphServiceServer) SearchVector(context.Context, *SearchVectorRequest) (*SearchVectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVector not implemented")
}
func (UnimplementedPolarGraphServiceServer) Reachable(context.Context, *ReachableRequest) (*ReachableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reachable not implemented")
}
func (UnimplementedPolarGraphServiceServer) RegisterNodeType(context.Context, *RegisterNodeTypeRequest) (*RegisterNodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNodeType not implemented")
}
func (UnimplementedPolarGraphServiceServer) GetNodeType(context.Context, *GetNodeTypeRequest) (*GetNodeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeType not implemented")
}
func (UnimplementedPolarGraphServiceServer) ListNodeTypes(context.Context, *ListNodeTypesRequest) (*ListNodeTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodeTypes not implemented")
}
func (UnimplementedPolarGraphServiceServer) ValidateNode(context.Context, *ValidateNodeRequest) (*ValidateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateNode not implemented")
}
func (UnimplementedPolarGraphServiceServer) RegisterEdgeType(context.Context, *RegisterEdgeTypeRequest) (*RegisterEdgeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEdgeType not implemented")
}
func (UnimplementedPolarGraphServiceServer) GetEdgeType(context.Context, *GetEdgeTypeRequest) (*GetEdgeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEdgeType not implemented")
}
func (UnimplementedPolarGraphServiceServer) ListEdgeTypes(context.Context, *ListEdgeTypesRequest) (*ListEdgeTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEdgeTypes not implemented")
}
func (UnimplementedPolarGraphServiceServer) ValidateEdge(context.Context, *ValidateEdgeRequest) (*ValidateEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateEdge not implemented")
}
func (UnimplementedPolarGraphServiceServer) ListPredicatesBetween(context.Context, *ListPredicatesBetweenRequest) (*ListPredicatesBetweenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPredicatesBetween not implemented")
}
func (UnimplementedPolarGraphServiceServer) SearchVectorFiltered(context.Context, *SearchVectorFilteredRequest) (*SearchVectorFilteredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVectorFiltered not implemented")
}
func (UnimplementedPolarGraphServiceServer) SearchVectorInSet(context.Context, *SearchVectorInSetRequest) (*SearchVectorInSetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchVectorInSet not implemented")
}
func (UnimplementedPolarGraphServiceServer) BatchInsertVectors(context.Context, *BatchInsertVectorsRequest) (*BatchInsertVectorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchInsertVectors not implemented")
}
func (UnimplementedPolarGraphServiceServer) VectorSeedQuery(context.Context, *VectorSeedQueryRequest) (*VectorSeedQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSeedQuery not implemented")
}
func (UnimplementedPolarGraphServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*CreateBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedPolarGraphServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedPolarGraphServiceServer) PurgeOldBackups(context.Context, *PurgeOldBackupsRequest) (*PurgeOldBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeOldBackups not implemented")
}
func (UnimplementedPolarGraphServiceServer) RunRetention(context.Context, *RunRetentionRequest) (*RunRetentionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunRetention not implemented")
}
func (UnimplementedPolarGraphServiceServer) ReplicaStatus(context.Context, *ReplicaStatusRequest) (*ReplicaStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplicaStatus not implemented")
}
func (UnimplementedPolarGraphServiceServer) StreamWal(*StreamWalRequest, grpc.ServerStreamingServer[WalEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamWal not implemented")
}
func (UnimplementedPolarGraphServiceServer) ExplainQuery(context.Context, *QueryRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainQuery not implemented")
}
func (UnimplementedPolarGraphServiceServer) MigrateSchema(context.Context, *MigrateRequest) (*MigrateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateSchema not implemented")
}
func (UnimplementedPolarGraphServiceServer) MigrationStatus(context.Context, *MigrationStatusRequest) (*MigrationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationStatus not implemented")
}
func (UnimplementedPolarGraphServiceServer) CypherQuery(context.Context, *CypherQueryRequest) (*CypherQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CypherQuery not implemented")
}
func (UnimplementedPolarGraphServiceServer) CypherWrite(context.Context, *CypherWriteRequest) (*CypherWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CypherWrite not implemented")
}
func (UnimplementedPolarGraphServiceServer) QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method QueryStream not implemented")
}
func (UnimplementedPolarGraphServiceServer) CypherQueryStream(*CypherQueryRequest, grpc.ServerStreamingServer[QueryStreamChunk]) error {
	return status.Error(codes.Unimplemented, "method CypherQueryStream not implemented")
}
func (UnimplementedPolarGraphServiceServer) mustEmbedUnimplementedPolarGraphServiceServer() {}
func (UnimplementedPolarGraphServiceServer) testEmbeddedByValue()                           {}

// UnsafePolarGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolarGraphServiceServer will
// result in compilation errors.
type UnsafePolarGraphServiceServer interface {
	mustEmbedUnimplementedPolarGraphServiceServer()
}

func RegisterPolarGraphServiceServer(s grpc.ServiceRegistrar, srv PolarGraphServiceServer) {
	// If the following call panics, it indicates UnimplementedPolarGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolarGraphService_ServiceDesc, srv)
}

func _PolarGraphService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_InsertVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).InsertVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_InsertVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).InsertVector(ctx, req.(*InsertVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_SearchVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).SearchVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_SearchVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).SearchVector(ctx, req.(*SearchVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_Reachable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReachableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).Reachable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_Reachable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).Reachable(ctx, req.(*ReachableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_RegisterNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).RegisterNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_RegisterNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).RegisterNodeType(ctx, req.(*RegisterNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_GetNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).GetNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_GetNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).GetNodeType(ctx, req.(*GetNodeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ListNodeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ListNodeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ListNodeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ListNodeTypes(ctx, req.(*ListNodeTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ValidateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ValidateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ValidateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ValidateNode(ctx, req.(*ValidateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_RegisterEdgeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEdgeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).RegisterEdgeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_RegisterEdgeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).RegisterEdgeType(ctx, req.(*RegisterEdgeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_GetEdgeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEdgeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).GetEdgeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_GetEdgeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).GetEdgeType(ctx, req.(*GetEdgeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ListEdgeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEdgeTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ListEdgeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ListEdgeTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ListEdgeTypes(ctx, req.(*ListEdgeTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ValidateEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ValidateEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ValidateEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ValidateEdge(ctx, req.(*ValidateEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ListPredicatesBetween_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPredicatesBetweenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ListPredicatesBetween(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ListPredicatesBetween_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ListPredicatesBetween(ctx, req.(*ListPredicatesBetweenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_SearchVectorFiltered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorFilteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).SearchVectorFiltered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_SearchVectorFiltered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).SearchVectorFiltered(ctx, req.(*SearchVectorFilteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_SearchVectorInSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchVectorInSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).SearchVectorInSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_SearchVectorInSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).SearchVectorInSet(ctx, req.(*SearchVectorInSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_BatchInsertVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).BatchInsertVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_BatchInsertVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).BatchInsertVectors(ctx, req.(*BatchInsertVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_VectorSeedQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSeedQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).VectorSeedQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_VectorSeedQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).VectorSeedQuery(ctx, req.(*VectorSeedQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_PurgeOldBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeOldBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).PurgeOldBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_PurgeOldBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).PurgeOldBackups(ctx, req.(*PurgeOldBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_RunRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).RunRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_RunRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).RunRetention(ctx, req.(*RunRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_ReplicaStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ReplicaStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ReplicaStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ReplicaStatus(ctx, req.(*ReplicaStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_StreamWal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolarGraphServiceServer).StreamWal(m, &grpc.GenericServerStream[StreamWalRequest, WalEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_StreamWalServer = grpc.ServerStreamingServer[WalEntry]

func _PolarGraphService_ExplainQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).ExplainQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_ExplainQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).ExplainQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_MigrateSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).MigrateSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_MigrateSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).MigrateSchema(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_MigrationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).MigrationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_MigrationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).MigrationStatus(ctx, req.(*MigrationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_CypherQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CypherQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).CypherQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_CypherQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).CypherQuery(ctx, req.(*CypherQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_CypherWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CypherWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolarGraphServiceServer).CypherWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolarGraphService_CypherWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolarGraphServiceServer).CypherWrite(ctx, req.(*CypherWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolarGraphService_QueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolarGraphServiceServer).QueryStream(m, &grpc.GenericServerStream[QueryRequest, QueryStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_QueryStreamServer = grpc.ServerStreamingServer[QueryStreamChunk]

func _PolarGraphService_CypherQueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CypherQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolarGraphServiceServer).CypherQueryStream(m, &grpc.GenericServerStream[CypherQueryRequest, QueryStreamChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolarGraphService_CypherQueryStreamServer = grpc.ServerStreamingServer[QueryStreamChunk]

// PolarGraphService_ServiceDesc is the grpc.ServiceDesc for PolarGraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolarGraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "polargraph.v1.PolarGraphService",
	HandlerType: (*PolarGraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _PolarGraphService_Insert_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _PolarGraphService_Query_Handler,
		},
		{
			MethodName: "InsertVector",
			Handler:    _PolarGraphService_InsertVector_Handler,
		},
		{
			MethodName: "SearchVector",
			Handler:    _PolarGraphService_SearchVector_Handler,
		},
		{
			MethodName: "Reachable",
			Handler:    _PolarGraphService_Reachable_Handler,
		},
		{
			MethodName: "RegisterNodeType",
			Handler:    _PolarGraphService_RegisterNodeType_Handler,
		},
		{
			MethodName: "GetNodeType",
			Handler:    _PolarGraphService_GetNodeType_Handler,
		},
		{
			MethodName: "ListNodeTypes",
			Handler:    _PolarGraphService_ListNodeTypes_Handler,
		},
		{
			MethodName: "ValidateNode",
			Handler:    _PolarGraphService_ValidateNode_Handler,
		},
		{
			MethodName: "RegisterEdgeType",
			Handler:    _PolarGraphService_RegisterEdgeType_Handler,
		},
		{
			MethodName: "GetEdgeType",
			Handler:    _PolarGraphService_GetEdgeType_Handler,
		},
		{
			MethodName: "ListEdgeTypes",
			Handler:    _PolarGraphService_ListEdgeTypes_Handler,
		},
		{
			MethodName: "ValidateEdge",
			Handler:    _PolarGraphService_ValidateEdge_Handler,
		},
		{
			MethodName: "ListPredicatesBetween",
			Handler:    _PolarGraphService_ListPredicatesBetween_Handler,
		},
		{
			MethodName: "SearchVectorFiltered",
			Handler:    _PolarGraphService_SearchVectorFiltered_Handler,
		},
		{
			MethodName: "SearchVectorInSet",
			Handler:    _PolarGraphService_SearchVectorInSet_Handler,
		},
		{
			MethodName: "BatchInsertVectors",
			Handler:    _PolarGraphService_BatchInsertVectors_Handler,
		},
		{
			MethodName: "VectorSeedQuery",
			Handler:    _PolarGraphService_VectorSeedQuery_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _PolarGraphService_CreateBackup_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _PolarGraphService_ListBackups_Handler,
		},
		{
			MethodName: "PurgeOldBackups",
			Handler:    _PolarGraphService_PurgeOldBackups_Handler,
		},
		{
			MethodName: "RunRetention",
			Handler:    _PolarGraphService_RunRetention_Handler,
		},
		{
			MethodName: "ReplicaStatus",
			Handler:    _PolarGraphService_ReplicaStatus_Handler,
		},
		{
			MethodName: "ExplainQuery",
			Handler:    _PolarGraphService_ExplainQuery_Handler,
		},
		{
			MethodName: "MigrateSchema",
			Handler:    _PolarGraphService_MigrateSchema_Handler,
		},
		{
			MethodName: "MigrationStatus",
			Handler:    _PolarGraphService_MigrationStatus_Handler,
		},
		{
			MethodName: "CypherQuery",
			Handler:    _PolarGraphService_CypherQuery_Handler,
		},
		{
			MethodName: "CypherWrite",
			Handler:    _PolarGraphService_CypherWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWal",
			Handler:       _PolarGraphService_StreamWal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "QueryStream",
			Handler:       _PolarGraphService_QueryStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CypherQueryStream",
			Handler:       _PolarGraphService_CypherQueryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "polargraph.proto",
}
