[package]
name        = "polargraph-query"
description = "Query planner and Datalog evaluator"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
rust-version.workspace = true

[dependencies]
polargraph-core    = { path = "../polargraph-core" }
polargraph-storage = { path = "../polargraph-storage" }
serde       = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
uuid        = { workspace = true }

[dev-dependencies]
tempfile    = { workspace = true }
