apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polargraph.fullname" . }}-config
  namespace: {{ include "polargraph.namespace" . }}
  labels:
    {{- include "polargraph.labels" . | nindent 4 }}
data:
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  RUST_LOG: {{ .Values.config.logLevel | quote }}
  POLARGRAPH_METRICS_PORT: {{ .Values.config.metricsPort | quote }}
  POLARGRAPH_GRPC_PORT: {{ .Values.config.grpcPort | quote }}
  POLARGRAPH_UI_PORT: {{ .Values.config.uiPort | quote }}
