{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polargraph.fullname" . }}-secrets
  namespace: {{ include "polargraph.namespace" . }}
  labels:
    {{- include "polargraph.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc | quote }}
{{- end }}
