apiVersion: v1
kind: Service
metadata:
  name: {{ include "polargraph.fullname" . }}-grpc
  namespace: {{ include "polargraph.namespace" . }}
  labels:
    {{- include "polargraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.grpc.type }}
  selector:
    {{- include "polargraph.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: 50051
      protocol: TCP
      appProtocol: grpc.h2
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polargraph.fullname" . }}-ui
  namespace: {{ include "polargraph.namespace" . }}
  labels:
    {{- include "polargraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ui.type }}
  selector:
    {{- include "polargraph.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.ui.port }}
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "polargraph.fullname" . }}-metrics
  namespace: {{ include "polargraph.namespace" . }}
  labels:
    {{- include "polargraph.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.metrics.type }}
  selector:
    {{- include "polargraph.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: 9090
      protocol: TCP
