apiVersion: v1
kind: Service
metadata:
  name: polargraph-grpc
  namespace: polargraph
  labels:
    app: polargraph
spec:
  type: ClusterIP
  selector:
    app: polargraph
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
      appProtocol: grpc.h2
---
apiVersion: v1
kind: Service
metadata:
  name: polargraph-ui
  namespace: polargraph
  labels:
    app: polargraph
spec:
  type: ClusterIP
  selector:
    app: polargraph
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: polargraph-metrics
  namespace: polargraph
  labels:
    app: polargraph
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: polargraph
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
